// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGnsVNtXwBWFTBIsYDEaqKi4wnH0xFAkE',
    appId: '1:187357394182:web:ba95d287188ce1d8a61a87',
    messagingSenderId: '187357394182',
    projectId: 'futter-todo-lab',
    authDomain: 'futter-todo-lab.firebaseapp.com',
    storageBucket: 'futter-todo-lab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhuAMeoKeFoC90P1uTSelLd0cl5ZnmGzg',
    appId: '1:187357394182:android:ba6b71769f88b65fa61a87',
    messagingSenderId: '187357394182',
    projectId: 'futter-todo-lab',
    storageBucket: 'futter-todo-lab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGpYkeDzGyogY2fCrX9Ugj2mT7GZDfCrI',
    appId: '1:187357394182:ios:92fa5927802a7de4a61a87',
    messagingSenderId: '187357394182',
    projectId: 'futter-todo-lab',
    storageBucket: 'futter-todo-lab.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGpYkeDzGyogY2fCrX9Ugj2mT7GZDfCrI',
    appId: '1:187357394182:ios:92fa5927802a7de4a61a87',
    messagingSenderId: '187357394182',
    projectId: 'futter-todo-lab',
    storageBucket: 'futter-todo-lab.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGnsVNtXwBWFTBIsYDEaqKi4wnH0xFAkE',
    appId: '1:187357394182:web:f34b41989faaffbba61a87',
    messagingSenderId: '187357394182',
    projectId: 'futter-todo-lab',
    authDomain: 'futter-todo-lab.firebaseapp.com',
    storageBucket: 'futter-todo-lab.appspot.com',
  );
}
